//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4.1.9004
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4.1.9004 D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g 2013-04-07 18:43:18

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;


using Antlr.Runtime.Tree;
using RewriteRuleITokenStream = Antlr.Runtime.Tree.RewriteRuleTokenStream;

namespace  LinqToQuerystring 
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4.1.9004")]
[System.CLSCompliant(false)]
public partial class LinqToQuerystringParser : Antlr.Runtime.Parser
{
	internal static readonly string[] tokenNames = new string[] {
		"<invalid>", "<EOR>", "<DOWN>", "<UP>", "ALLPAGES", "AND", "ASC", "ASSIGN", "BOOL", "DATETIME", "DESC", "EQUALS", "FILTER", "GREATERTHAN", "GREATERTHANOREQUAL", "IDENTIFIER", "INLINECOUNT", "INT", "LESSTHAN", "LESSTHANOREQUAL", "NEWLINE", "NONE", "NOT", "NOTEQUALS", "OR", "ORDERBY", "SELECT", "SKIP", "SPACE", "STRING", "TOP", "'&'", "'('", "')'", "','", "'/'"
	};
	public const int EOF=-1;
	public const int ALLPAGES=4;
	public const int AND=5;
	public const int ASC=6;
	public const int ASSIGN=7;
	public const int BOOL=8;
	public const int DATETIME=9;
	public const int DESC=10;
	public const int EQUALS=11;
	public const int FILTER=12;
	public const int GREATERTHAN=13;
	public const int GREATERTHANOREQUAL=14;
	public const int IDENTIFIER=15;
	public const int INLINECOUNT=16;
	public const int INT=17;
	public const int LESSTHAN=18;
	public const int LESSTHANOREQUAL=19;
	public const int NEWLINE=20;
	public const int NONE=21;
	public const int NOT=22;
	public const int NOTEQUALS=23;
	public const int OR=24;
	public const int ORDERBY=25;
	public const int SELECT=26;
	public const int SKIP=27;
	public const int SPACE=28;
	public const int STRING=29;
	public const int TOP=30;
	public const int T__31=31;
	public const int T__32=32;
	public const int T__33=33;
	public const int T__34=34;
	public const int T__35=35;

	public LinqToQuerystringParser(ITokenStream input)
		: this(input, new RecognizerSharedState())
	{
	}
	public LinqToQuerystringParser(ITokenStream input, RecognizerSharedState state)
		: base(input, state)
	{
		ITreeAdaptor treeAdaptor = default(ITreeAdaptor);
		CreateTreeAdaptor(ref treeAdaptor);
		TreeAdaptor = treeAdaptor ?? new CommonTreeAdaptor();
		OnCreated();
	}
	// Implement this function in your helper file to use a custom tree adaptor
	partial void CreateTreeAdaptor(ref ITreeAdaptor adaptor);

	private ITreeAdaptor adaptor;

	public ITreeAdaptor TreeAdaptor
	{
		get
		{
			return adaptor;
		}

		set
		{
			this.adaptor = value;
		}
	}

	public override string[] TokenNames { get { return LinqToQuerystringParser.tokenNames; } }
	public override string GrammarFileName { get { return "D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	#region Rules
	partial void EnterRule_prog();
	partial void LeaveRule_prog();
	// $ANTLR start "prog"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:13:8: public prog : ( param ( '&' ! param )* )* ;
	[GrammarRule("prog")]
	public AstParserRuleReturnScope<object, IToken> prog()
	{
		EnterRule_prog();
		EnterRule("prog", 1);
		TraceIn("prog", 1);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken char_literal2 = default(IToken);
		AstParserRuleReturnScope<object, IToken> param1 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> param3 = default(AstParserRuleReturnScope<object, IToken>);

		object char_literal2_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "prog");
		DebugLocation(13, 25);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:14:2: ( ( param ( '&' ! param )* )* )
			DebugEnterAlt(1);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:14:4: ( param ( '&' ! param )* )*
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(14, 4);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:14:4: ( param ( '&' ! param )* )*
			try { DebugEnterSubRule(2);
			while (true)
			{
				int alt2=2;
				try { DebugEnterDecision(2, false);
				int LA2_1 = input.LA(1);

				if ((LA2_1==FILTER||LA2_1==INLINECOUNT||(LA2_1>=ORDERBY && LA2_1<=SKIP)||LA2_1==TOP))
				{
					alt2 = 1;
				}


				} finally { DebugExitDecision(2); }
				switch ( alt2 )
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:14:5: param ( '&' ! param )*
					{
					DebugLocation(14, 5);
					PushFollow(Follow._param_in_prog55);
					param1=param();
					PopFollow();

					adaptor.AddChild(root_0, param1.Tree);
					DebugLocation(14, 11);
					// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:14:11: ( '&' ! param )*
					try { DebugEnterSubRule(1);
					while (true)
					{
						int alt1=2;
						try { DebugEnterDecision(1, false);
						int LA1_1 = input.LA(1);

						if ((LA1_1==31))
						{
							alt1 = 1;
						}


						} finally { DebugExitDecision(1); }
						switch ( alt1 )
						{
						case 1:
							DebugEnterAlt(1);
							// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:14:12: '&' ! param
							{
							DebugLocation(14, 15);
							char_literal2=(IToken)Match(input,31,Follow._31_in_prog58); 
							DebugLocation(14, 17);
							PushFollow(Follow._param_in_prog61);
							param3=param();
							PopFollow();

							adaptor.AddChild(root_0, param3.Tree);

							}
							break;

						default:
							goto loop1;
						}
					}

					loop1:
						;

					} finally { DebugExitSubRule(1); }


					}
					break;

				default:
					goto loop2;
				}
			}

			loop2:
				;

			} finally { DebugExitSubRule(2); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("prog", 1);
			LeaveRule("prog", 1);
			LeaveRule_prog();
		}
		DebugLocation(14, 25);
		} finally { DebugExitRule(GrammarFileName, "prog"); }
		return retval;

	}
	// $ANTLR end "prog"

	partial void EnterRule_param();
	partial void LeaveRule_param();
	// $ANTLR start "param"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:16:1: param : ( orderby | top | skip | filter | select | inlinecount ) ;
	[GrammarRule("param")]
	private AstParserRuleReturnScope<object, IToken> param()
	{
		EnterRule_param();
		EnterRule("param", 2);
		TraceIn("param", 2);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		AstParserRuleReturnScope<object, IToken> orderby4 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> top5 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> skip6 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> filter7 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> select8 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> inlinecount9 = default(AstParserRuleReturnScope<object, IToken>);

		try { DebugEnterRule(GrammarFileName, "param");
		DebugLocation(16, 62);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:16:7: ( ( orderby | top | skip | filter | select | inlinecount ) )
			DebugEnterAlt(1);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:16:9: ( orderby | top | skip | filter | select | inlinecount )
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(16, 9);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:16:9: ( orderby | top | skip | filter | select | inlinecount )
			int alt3=6;
			try { DebugEnterSubRule(3);
			try { DebugEnterDecision(3, false);
			switch (input.LA(1))
			{
			case ORDERBY:
				{
				alt3 = 1;
				}
				break;
			case TOP:
				{
				alt3 = 2;
				}
				break;
			case SKIP:
				{
				alt3 = 3;
				}
				break;
			case FILTER:
				{
				alt3 = 4;
				}
				break;
			case SELECT:
				{
				alt3 = 5;
				}
				break;
			case INLINECOUNT:
				{
				alt3 = 6;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 3, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(3); }
			switch (alt3)
			{
			case 1:
				DebugEnterAlt(1);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:16:10: orderby
				{
				DebugLocation(16, 10);
				PushFollow(Follow._orderby_in_param74);
				orderby4=orderby();
				PopFollow();

				adaptor.AddChild(root_0, orderby4.Tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:16:20: top
				{
				DebugLocation(16, 20);
				PushFollow(Follow._top_in_param78);
				top5=top();
				PopFollow();

				adaptor.AddChild(root_0, top5.Tree);

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:16:26: skip
				{
				DebugLocation(16, 26);
				PushFollow(Follow._skip_in_param82);
				skip6=skip();
				PopFollow();

				adaptor.AddChild(root_0, skip6.Tree);

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:16:33: filter
				{
				DebugLocation(16, 33);
				PushFollow(Follow._filter_in_param86);
				filter7=filter();
				PopFollow();

				adaptor.AddChild(root_0, filter7.Tree);

				}
				break;
			case 5:
				DebugEnterAlt(5);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:16:42: select
				{
				DebugLocation(16, 42);
				PushFollow(Follow._select_in_param90);
				select8=select();
				PopFollow();

				adaptor.AddChild(root_0, select8.Tree);

				}
				break;
			case 6:
				DebugEnterAlt(6);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:16:51: inlinecount
				{
				DebugLocation(16, 51);
				PushFollow(Follow._inlinecount_in_param94);
				inlinecount9=inlinecount();
				PopFollow();

				adaptor.AddChild(root_0, inlinecount9.Tree);

				}
				break;

			}
			} finally { DebugExitSubRule(3); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("param", 2);
			LeaveRule("param", 2);
			LeaveRule_param();
		}
		DebugLocation(16, 62);
		} finally { DebugExitRule(GrammarFileName, "param"); }
		return retval;

	}
	// $ANTLR end "param"

	partial void EnterRule_skip();
	partial void LeaveRule_skip();
	// $ANTLR start "skip"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:18:1: skip : SKIP ^ ( INT )+ ;
	[GrammarRule("skip")]
	private AstParserRuleReturnScope<object, IToken> skip()
	{
		EnterRule_skip();
		EnterRule("skip", 3);
		TraceIn("skip", 3);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken SKIP10 = default(IToken);
		IToken INT11 = default(IToken);

		object SKIP10_tree = default(object);
		object INT11_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "skip");
		DebugLocation(18, 13);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:19:2: ( SKIP ^ ( INT )+ )
			DebugEnterAlt(1);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:19:4: SKIP ^ ( INT )+
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(19, 8);
			SKIP10=(IToken)Match(input,SKIP,Follow._SKIP_in_skip105); 
			SKIP10_tree = (object)adaptor.Create(SKIP10);
			root_0 = (object)adaptor.BecomeRoot(SKIP10_tree, root_0);
			DebugLocation(19, 10);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:19:10: ( INT )+
			int cnt4=0;
			try { DebugEnterSubRule(4);
			while (true)
			{
				int alt4=2;
				try { DebugEnterDecision(4, false);
				int LA4_1 = input.LA(1);

				if ((LA4_1==INT))
				{
					alt4 = 1;
				}


				} finally { DebugExitDecision(4); }
				switch (alt4)
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:19:10: INT
					{
					DebugLocation(19, 10);
					INT11=(IToken)Match(input,INT,Follow._INT_in_skip108); 
					INT11_tree = (object)adaptor.Create(INT11);
					adaptor.AddChild(root_0, INT11_tree);

					}
					break;

				default:
					if (cnt4 >= 1)
						goto loop4;

					EarlyExitException eee4 = new EarlyExitException( 4, input );
					DebugRecognitionException(eee4);
					throw eee4;
				}
				cnt4++;
			}
			loop4:
				;

			} finally { DebugExitSubRule(4); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("skip", 3);
			LeaveRule("skip", 3);
			LeaveRule_skip();
		}
		DebugLocation(19, 13);
		} finally { DebugExitRule(GrammarFileName, "skip"); }
		return retval;

	}
	// $ANTLR end "skip"

	partial void EnterRule_top();
	partial void LeaveRule_top();
	// $ANTLR start "top"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:21:1: top : TOP ^ ( INT )+ ;
	[GrammarRule("top")]
	private AstParserRuleReturnScope<object, IToken> top()
	{
		EnterRule_top();
		EnterRule("top", 4);
		TraceIn("top", 4);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken TOP12 = default(IToken);
		IToken INT13 = default(IToken);

		object TOP12_tree = default(object);
		object INT13_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "top");
		DebugLocation(21, 12);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:22:2: ( TOP ^ ( INT )+ )
			DebugEnterAlt(1);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:22:4: TOP ^ ( INT )+
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(22, 7);
			TOP12=(IToken)Match(input,TOP,Follow._TOP_in_top119); 
			TOP12_tree = (object)adaptor.Create(TOP12);
			root_0 = (object)adaptor.BecomeRoot(TOP12_tree, root_0);
			DebugLocation(22, 9);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:22:9: ( INT )+
			int cnt5=0;
			try { DebugEnterSubRule(5);
			while (true)
			{
				int alt5=2;
				try { DebugEnterDecision(5, false);
				int LA5_1 = input.LA(1);

				if ((LA5_1==INT))
				{
					alt5 = 1;
				}


				} finally { DebugExitDecision(5); }
				switch (alt5)
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:22:9: INT
					{
					DebugLocation(22, 9);
					INT13=(IToken)Match(input,INT,Follow._INT_in_top122); 
					INT13_tree = (object)adaptor.Create(INT13);
					adaptor.AddChild(root_0, INT13_tree);

					}
					break;

				default:
					if (cnt5 >= 1)
						goto loop5;

					EarlyExitException eee5 = new EarlyExitException( 5, input );
					DebugRecognitionException(eee5);
					throw eee5;
				}
				cnt5++;
			}
			loop5:
				;

			} finally { DebugExitSubRule(5); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("top", 4);
			LeaveRule("top", 4);
			LeaveRule_top();
		}
		DebugLocation(22, 12);
		} finally { DebugExitRule(GrammarFileName, "top"); }
		return retval;

	}
	// $ANTLR end "top"

	partial void EnterRule_filter();
	partial void LeaveRule_filter();
	// $ANTLR start "filter"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:24:1: filter : FILTER ^ filterexpression ;
	[GrammarRule("filter")]
	private AstParserRuleReturnScope<object, IToken> filter()
	{
		EnterRule_filter();
		EnterRule("filter", 5);
		TraceIn("filter", 5);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken FILTER14 = default(IToken);
		AstParserRuleReturnScope<object, IToken> filterexpression15 = default(AstParserRuleReturnScope<object, IToken>);

		object FILTER14_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "filter");
		DebugLocation(24, 27);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:25:2: ( FILTER ^ filterexpression )
			DebugEnterAlt(1);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:25:4: FILTER ^ filterexpression
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(25, 10);
			FILTER14=(IToken)Match(input,FILTER,Follow._FILTER_in_filter133); 
			FILTER14_tree = (object)adaptor.Create(FILTER14);
			root_0 = (object)adaptor.BecomeRoot(FILTER14_tree, root_0);
			DebugLocation(25, 12);
			PushFollow(Follow._filterexpression_in_filter136);
			filterexpression15=filterexpression();
			PopFollow();

			adaptor.AddChild(root_0, filterexpression15.Tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("filter", 5);
			LeaveRule("filter", 5);
			LeaveRule_filter();
		}
		DebugLocation(25, 27);
		} finally { DebugExitRule(GrammarFileName, "filter"); }
		return retval;

	}
	// $ANTLR end "filter"

	partial void EnterRule_select();
	partial void LeaveRule_select();
	// $ANTLR start "select"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:27:1: select : SELECT ^ propertyname ( ',' ! propertyname )* ;
	[GrammarRule("select")]
	private AstParserRuleReturnScope<object, IToken> select()
	{
		EnterRule_select();
		EnterRule("select", 6);
		TraceIn("select", 6);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken SELECT16 = default(IToken);
		IToken char_literal18 = default(IToken);
		AstParserRuleReturnScope<object, IToken> propertyname17 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> propertyname19 = default(AstParserRuleReturnScope<object, IToken>);

		object SELECT16_tree = default(object);
		object char_literal18_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "select");
		DebugLocation(27, 44);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:28:2: ( SELECT ^ propertyname ( ',' ! propertyname )* )
			DebugEnterAlt(1);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:28:4: SELECT ^ propertyname ( ',' ! propertyname )*
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(28, 10);
			SELECT16=(IToken)Match(input,SELECT,Follow._SELECT_in_select146); 
			SELECT16_tree = (object)adaptor.Create(SELECT16);
			root_0 = (object)adaptor.BecomeRoot(SELECT16_tree, root_0);
			DebugLocation(28, 12);
			PushFollow(Follow._propertyname_in_select149);
			propertyname17=propertyname();
			PopFollow();

			adaptor.AddChild(root_0, propertyname17.Tree);
			DebugLocation(28, 25);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:28:25: ( ',' ! propertyname )*
			try { DebugEnterSubRule(6);
			while (true)
			{
				int alt6=2;
				try { DebugEnterDecision(6, false);
				int LA6_1 = input.LA(1);

				if ((LA6_1==34))
				{
					alt6 = 1;
				}


				} finally { DebugExitDecision(6); }
				switch ( alt6 )
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:28:26: ',' ! propertyname
					{
					DebugLocation(28, 29);
					char_literal18=(IToken)Match(input,34,Follow._34_in_select152); 
					DebugLocation(28, 31);
					PushFollow(Follow._propertyname_in_select155);
					propertyname19=propertyname();
					PopFollow();

					adaptor.AddChild(root_0, propertyname19.Tree);

					}
					break;

				default:
					goto loop6;
				}
			}

			loop6:
				;

			} finally { DebugExitSubRule(6); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("select", 6);
			LeaveRule("select", 6);
			LeaveRule_select();
		}
		DebugLocation(28, 44);
		} finally { DebugExitRule(GrammarFileName, "select"); }
		return retval;

	}
	// $ANTLR end "select"

	partial void EnterRule_inlinecount();
	partial void LeaveRule_inlinecount();
	// $ANTLR start "inlinecount"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:30:1: inlinecount : ( INLINECOUNT ^ ALLPAGES | INLINECOUNT NONE ->);
	[GrammarRule("inlinecount")]
	private AstParserRuleReturnScope<object, IToken> inlinecount()
	{
		EnterRule_inlinecount();
		EnterRule("inlinecount", 7);
		TraceIn("inlinecount", 7);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken INLINECOUNT20 = default(IToken);
		IToken ALLPAGES21 = default(IToken);
		IToken INLINECOUNT22 = default(IToken);
		IToken NONE23 = default(IToken);

		object INLINECOUNT20_tree = default(object);
		object ALLPAGES21_tree = default(object);
		object INLINECOUNT22_tree = default(object);
		object NONE23_tree = default(object);
		RewriteRuleITokenStream stream_INLINECOUNT=new RewriteRuleITokenStream(adaptor,"token INLINECOUNT");
		RewriteRuleITokenStream stream_NONE=new RewriteRuleITokenStream(adaptor,"token NONE");
		try { DebugEnterRule(GrammarFileName, "inlinecount");
		DebugLocation(30, 22);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:31:2: ( INLINECOUNT ^ ALLPAGES | INLINECOUNT NONE ->)
			int alt7=2;
			try { DebugEnterDecision(7, false);
			int LA7_1 = input.LA(1);

			if ((LA7_1==INLINECOUNT))
			{
				int LA7_2 = input.LA(2);

				if ((LA7_2==ALLPAGES))
				{
					alt7 = 1;
				}
				else if ((LA7_2==NONE))
				{
					alt7 = 2;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 7, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 7, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(7); }
			switch (alt7)
			{
			case 1:
				DebugEnterAlt(1);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:31:4: INLINECOUNT ^ ALLPAGES
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(31, 15);
				INLINECOUNT20=(IToken)Match(input,INLINECOUNT,Follow._INLINECOUNT_in_inlinecount167); 
				INLINECOUNT20_tree = (object)adaptor.Create(INLINECOUNT20);
				root_0 = (object)adaptor.BecomeRoot(INLINECOUNT20_tree, root_0);
				DebugLocation(31, 17);
				ALLPAGES21=(IToken)Match(input,ALLPAGES,Follow._ALLPAGES_in_inlinecount170); 
				ALLPAGES21_tree = (object)adaptor.Create(ALLPAGES21);
				adaptor.AddChild(root_0, ALLPAGES21_tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:32:4: INLINECOUNT NONE
				{
				DebugLocation(32, 4);
				INLINECOUNT22=(IToken)Match(input,INLINECOUNT,Follow._INLINECOUNT_in_inlinecount175);  
				stream_INLINECOUNT.Add(INLINECOUNT22);

				DebugLocation(32, 16);
				NONE23=(IToken)Match(input,NONE,Follow._NONE_in_inlinecount177);  
				stream_NONE.Add(NONE23);



				{
				// AST REWRITE
				// elements: 
				// token labels: 
				// rule labels: retval
				// token list labels: 
				// rule list labels: 
				// wildcard labels: 
				retval.Tree = root_0;
				RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

				root_0 = (object)adaptor.Nil();
				// 32:21: ->
				{
					DebugLocation(32, 23);
					root_0 = null;
				}

				retval.Tree = root_0;
				}

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("inlinecount", 7);
			LeaveRule("inlinecount", 7);
			LeaveRule_inlinecount();
		}
		DebugLocation(32, 22);
		} finally { DebugExitRule(GrammarFileName, "inlinecount"); }
		return retval;

	}
	// $ANTLR end "inlinecount"

	partial void EnterRule_filterexpression();
	partial void LeaveRule_filterexpression();
	// $ANTLR start "filterexpression"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:34:1: filterexpression : orexpression ( SPACE ! OR ^ SPACE ! orexpression )* ;
	[GrammarRule("filterexpression")]
	private AstParserRuleReturnScope<object, IToken> filterexpression()
	{
		EnterRule_filterexpression();
		EnterRule("filterexpression", 8);
		TraceIn("filterexpression", 8);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken SPACE25 = default(IToken);
		IToken OR26 = default(IToken);
		IToken SPACE27 = default(IToken);
		AstParserRuleReturnScope<object, IToken> orexpression24 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> orexpression28 = default(AstParserRuleReturnScope<object, IToken>);

		object SPACE25_tree = default(object);
		object OR26_tree = default(object);
		object SPACE27_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "filterexpression");
		DebugLocation(34, 49);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:35:2: ( orexpression ( SPACE ! OR ^ SPACE ! orexpression )* )
			DebugEnterAlt(1);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:35:4: orexpression ( SPACE ! OR ^ SPACE ! orexpression )*
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(35, 4);
			PushFollow(Follow._orexpression_in_filterexpression189);
			orexpression24=orexpression();
			PopFollow();

			adaptor.AddChild(root_0, orexpression24.Tree);
			DebugLocation(35, 17);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:35:17: ( SPACE ! OR ^ SPACE ! orexpression )*
			try { DebugEnterSubRule(8);
			while (true)
			{
				int alt8=2;
				try { DebugEnterDecision(8, false);
				int LA8_1 = input.LA(1);

				if ((LA8_1==SPACE))
				{
					alt8 = 1;
				}


				} finally { DebugExitDecision(8); }
				switch ( alt8 )
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:35:18: SPACE ! OR ^ SPACE ! orexpression
					{
					DebugLocation(35, 23);
					SPACE25=(IToken)Match(input,SPACE,Follow._SPACE_in_filterexpression192); 
					DebugLocation(35, 27);
					OR26=(IToken)Match(input,OR,Follow._OR_in_filterexpression195); 
					OR26_tree = (object)adaptor.Create(OR26);
					root_0 = (object)adaptor.BecomeRoot(OR26_tree, root_0);
					DebugLocation(35, 34);
					SPACE27=(IToken)Match(input,SPACE,Follow._SPACE_in_filterexpression198); 
					DebugLocation(35, 36);
					PushFollow(Follow._orexpression_in_filterexpression201);
					orexpression28=orexpression();
					PopFollow();

					adaptor.AddChild(root_0, orexpression28.Tree);

					}
					break;

				default:
					goto loop8;
				}
			}

			loop8:
				;

			} finally { DebugExitSubRule(8); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("filterexpression", 8);
			LeaveRule("filterexpression", 8);
			LeaveRule_filterexpression();
		}
		DebugLocation(35, 49);
		} finally { DebugExitRule(GrammarFileName, "filterexpression"); }
		return retval;

	}
	// $ANTLR end "filterexpression"

	partial void EnterRule_orexpression();
	partial void LeaveRule_orexpression();
	// $ANTLR start "orexpression"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:37:1: orexpression : andexpression ( SPACE ! AND ^ SPACE ! andexpression )* ;
	[GrammarRule("orexpression")]
	private AstParserRuleReturnScope<object, IToken> orexpression()
	{
		EnterRule_orexpression();
		EnterRule("orexpression", 9);
		TraceIn("orexpression", 9);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken SPACE30 = default(IToken);
		IToken AND31 = default(IToken);
		IToken SPACE32 = default(IToken);
		AstParserRuleReturnScope<object, IToken> andexpression29 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> andexpression33 = default(AstParserRuleReturnScope<object, IToken>);

		object SPACE30_tree = default(object);
		object AND31_tree = default(object);
		object SPACE32_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "orexpression");
		DebugLocation(37, 52);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:38:2: ( andexpression ( SPACE ! AND ^ SPACE ! andexpression )* )
			DebugEnterAlt(1);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:38:4: andexpression ( SPACE ! AND ^ SPACE ! andexpression )*
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(38, 4);
			PushFollow(Follow._andexpression_in_orexpression213);
			andexpression29=andexpression();
			PopFollow();

			adaptor.AddChild(root_0, andexpression29.Tree);
			DebugLocation(38, 18);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:38:18: ( SPACE ! AND ^ SPACE ! andexpression )*
			try { DebugEnterSubRule(9);
			while (true)
			{
				int alt9=2;
				try { DebugEnterDecision(9, false);
				int LA9_1 = input.LA(1);

				if ((LA9_1==SPACE))
				{
					int LA9_2 = input.LA(2);

					if ((LA9_2==AND))
					{
						alt9 = 1;
					}


				}


				} finally { DebugExitDecision(9); }
				switch ( alt9 )
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:38:19: SPACE ! AND ^ SPACE ! andexpression
					{
					DebugLocation(38, 24);
					SPACE30=(IToken)Match(input,SPACE,Follow._SPACE_in_orexpression216); 
					DebugLocation(38, 29);
					AND31=(IToken)Match(input,AND,Follow._AND_in_orexpression219); 
					AND31_tree = (object)adaptor.Create(AND31);
					root_0 = (object)adaptor.BecomeRoot(AND31_tree, root_0);
					DebugLocation(38, 36);
					SPACE32=(IToken)Match(input,SPACE,Follow._SPACE_in_orexpression222); 
					DebugLocation(38, 38);
					PushFollow(Follow._andexpression_in_orexpression225);
					andexpression33=andexpression();
					PopFollow();

					adaptor.AddChild(root_0, andexpression33.Tree);

					}
					break;

				default:
					goto loop9;
				}
			}

			loop9:
				;

			} finally { DebugExitSubRule(9); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("orexpression", 9);
			LeaveRule("orexpression", 9);
			LeaveRule_orexpression();
		}
		DebugLocation(38, 52);
		} finally { DebugExitRule(GrammarFileName, "orexpression"); }
		return retval;

	}
	// $ANTLR end "orexpression"

	partial void EnterRule_andexpression();
	partial void LeaveRule_andexpression();
	// $ANTLR start "andexpression"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:40:1: andexpression : ( NOT ^ SPACE booleanexpression | booleanexpression );
	[GrammarRule("andexpression")]
	private AstParserRuleReturnScope<object, IToken> andexpression()
	{
		EnterRule_andexpression();
		EnterRule("andexpression", 10);
		TraceIn("andexpression", 10);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken NOT34 = default(IToken);
		IToken SPACE35 = default(IToken);
		AstParserRuleReturnScope<object, IToken> booleanexpression36 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> booleanexpression37 = default(AstParserRuleReturnScope<object, IToken>);

		object NOT34_tree = default(object);
		object SPACE35_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "andexpression");
		DebugLocation(40, 20);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:41:2: ( NOT ^ SPACE booleanexpression | booleanexpression )
			int alt10=2;
			try { DebugEnterDecision(10, false);
			int LA10_1 = input.LA(1);

			if ((LA10_1==NOT))
			{
				alt10 = 1;
			}
			else if (((LA10_1>=BOOL && LA10_1<=DATETIME)||LA10_1==IDENTIFIER||LA10_1==INT||LA10_1==STRING||LA10_1==32))
			{
				alt10 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 10, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(10); }
			switch (alt10)
			{
			case 1:
				DebugEnterAlt(1);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:41:4: NOT ^ SPACE booleanexpression
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(41, 7);
				NOT34=(IToken)Match(input,NOT,Follow._NOT_in_andexpression237); 
				NOT34_tree = (object)adaptor.Create(NOT34);
				root_0 = (object)adaptor.BecomeRoot(NOT34_tree, root_0);
				DebugLocation(41, 9);
				SPACE35=(IToken)Match(input,SPACE,Follow._SPACE_in_andexpression240); 
				SPACE35_tree = (object)adaptor.Create(SPACE35);
				adaptor.AddChild(root_0, SPACE35_tree);
				DebugLocation(41, 15);
				PushFollow(Follow._booleanexpression_in_andexpression242);
				booleanexpression36=booleanexpression();
				PopFollow();

				adaptor.AddChild(root_0, booleanexpression36.Tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:42:4: booleanexpression
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(42, 4);
				PushFollow(Follow._booleanexpression_in_andexpression247);
				booleanexpression37=booleanexpression();
				PopFollow();

				adaptor.AddChild(root_0, booleanexpression37.Tree);

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("andexpression", 10);
			LeaveRule("andexpression", 10);
			LeaveRule_andexpression();
		}
		DebugLocation(42, 20);
		} finally { DebugExitRule(GrammarFileName, "andexpression"); }
		return retval;

	}
	// $ANTLR end "andexpression"

	partial void EnterRule_booleanexpression();
	partial void LeaveRule_booleanexpression();
	// $ANTLR start "booleanexpression"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:44:1: booleanexpression : atom ( SPACE ! filteroperator ^ SPACE ! atom | implicit ) ;
	[GrammarRule("booleanexpression")]
	private AstParserRuleReturnScope<object, IToken> booleanexpression()
	{
		EnterRule_booleanexpression();
		EnterRule("booleanexpression", 11);
		TraceIn("booleanexpression", 11);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken SPACE39 = default(IToken);
		IToken SPACE41 = default(IToken);
		AstParserRuleReturnScope<object, IToken> atom38 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> filteroperator40 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> atom42 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> implicit43 = default(AstParserRuleReturnScope<object, IToken>);

		object SPACE39_tree = default(object);
		object SPACE41_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "booleanexpression");
		DebugLocation(44, 55);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:45:2: ( atom ( SPACE ! filteroperator ^ SPACE ! atom | implicit ) )
			DebugEnterAlt(1);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:45:4: atom ( SPACE ! filteroperator ^ SPACE ! atom | implicit )
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(45, 4);
			PushFollow(Follow._atom_in_booleanexpression258);
			atom38=atom();
			PopFollow();

			adaptor.AddChild(root_0, atom38.Tree);
			DebugLocation(45, 9);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:45:9: ( SPACE ! filteroperator ^ SPACE ! atom | implicit )
			int alt11=2;
			try { DebugEnterSubRule(11);
			try { DebugEnterDecision(11, false);
			int LA11_1 = input.LA(1);

			if ((LA11_1==SPACE))
			{
				int LA11_2 = input.LA(2);

				if ((LA11_2==AND||LA11_2==OR))
				{
					alt11 = 2;
				}
				else if ((LA11_2==EQUALS||(LA11_2>=GREATERTHAN && LA11_2<=GREATERTHANOREQUAL)||(LA11_2>=LESSTHAN && LA11_2<=LESSTHANOREQUAL)||LA11_2==NOTEQUALS))
				{
					alt11 = 1;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 11, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else if ((LA11_1==EOF||LA11_1==FILTER||LA11_1==INLINECOUNT||(LA11_1>=ORDERBY && LA11_1<=SKIP)||(LA11_1>=TOP && LA11_1<=31)||LA11_1==33))
			{
				alt11 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 11, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(11); }
			switch (alt11)
			{
			case 1:
				DebugEnterAlt(1);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:45:10: SPACE ! filteroperator ^ SPACE ! atom
				{
				DebugLocation(45, 15);
				SPACE39=(IToken)Match(input,SPACE,Follow._SPACE_in_booleanexpression261); 
				DebugLocation(45, 31);
				PushFollow(Follow._filteroperator_in_booleanexpression264);
				filteroperator40=filteroperator();
				PopFollow();

				root_0 = (object)adaptor.BecomeRoot(filteroperator40.Tree, root_0);
				DebugLocation(45, 38);
				SPACE41=(IToken)Match(input,SPACE,Follow._SPACE_in_booleanexpression267); 
				DebugLocation(45, 40);
				PushFollow(Follow._atom_in_booleanexpression270);
				atom42=atom();
				PopFollow();

				adaptor.AddChild(root_0, atom42.Tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:45:47: implicit
				{
				DebugLocation(45, 47);
				PushFollow(Follow._implicit_in_booleanexpression274);
				implicit43=@implicit();
				PopFollow();

				adaptor.AddChild(root_0, implicit43.Tree);

				}
				break;

			}
			} finally { DebugExitSubRule(11); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("booleanexpression", 11);
			LeaveRule("booleanexpression", 11);
			LeaveRule_booleanexpression();
		}
		DebugLocation(45, 55);
		} finally { DebugExitRule(GrammarFileName, "booleanexpression"); }
		return retval;

	}
	// $ANTLR end "booleanexpression"

	partial void EnterRule_implicit();
	partial void LeaveRule_implicit();
	// $ANTLR start "implicit"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:47:1: implicit : -> ^( EQUALS BOOL[\"true\"] ) ;
	[GrammarRule("implicit")]
	private AstParserRuleReturnScope<object, IToken> @implicit()
	{
		EnterRule_implicit();
		EnterRule("implicit", 12);
		TraceIn("implicit", 12);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		try { DebugEnterRule(GrammarFileName, "implicit");
		DebugLocation(47, 28);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:48:2: ( -> ^( EQUALS BOOL[\"true\"] ) )
			DebugEnterAlt(1);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:48:4: 
			{

			{
			// AST REWRITE
			// elements: 
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 48:4: -> ^( EQUALS BOOL[\"true\"] )
			{
				DebugLocation(48, 7);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:48:7: ^( EQUALS BOOL[\"true\"] )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(48, 9);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(EQUALS, "EQUALS"), root_1);

				DebugLocation(48, 16);
				adaptor.AddChild(root_1, (object)adaptor.Create(BOOL, "true"));

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("implicit", 12);
			LeaveRule("implicit", 12);
			LeaveRule_implicit();
		}
		DebugLocation(48, 28);
		} finally { DebugExitRule(GrammarFileName, "implicit"); }
		return retval;

	}
	// $ANTLR end "implicit"

	partial void EnterRule_atom();
	partial void LeaveRule_atom();
	// $ANTLR start "atom"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:50:1: atom : ( propertyname | '(' filterexpression ')' | ( ( INT )+ | BOOL | STRING | DATETIME ) );
	[GrammarRule("atom")]
	private AstParserRuleReturnScope<object, IToken> atom()
	{
		EnterRule_atom();
		EnterRule("atom", 13);
		TraceIn("atom", 13);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken char_literal45 = default(IToken);
		IToken char_literal47 = default(IToken);
		IToken INT48 = default(IToken);
		IToken BOOL49 = default(IToken);
		IToken STRING50 = default(IToken);
		IToken DATETIME51 = default(IToken);
		AstParserRuleReturnScope<object, IToken> propertyname44 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> filterexpression46 = default(AstParserRuleReturnScope<object, IToken>);

		object char_literal45_tree = default(object);
		object char_literal47_tree = default(object);
		object INT48_tree = default(object);
		object BOOL49_tree = default(object);
		object STRING50_tree = default(object);
		object DATETIME51_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "atom");
		DebugLocation(50, 36);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:50:6: ( propertyname | '(' filterexpression ')' | ( ( INT )+ | BOOL | STRING | DATETIME ) )
			int alt14=3;
			try { DebugEnterDecision(14, false);
			switch (input.LA(1))
			{
			case IDENTIFIER:
				{
				alt14 = 1;
				}
				break;
			case 32:
				{
				alt14 = 2;
				}
				break;
			case BOOL:
			case DATETIME:
			case INT:
			case STRING:
				{
				alt14 = 3;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 14, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(14); }
			switch (alt14)
			{
			case 1:
				DebugEnterAlt(1);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:50:8: propertyname
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(50, 8);
				PushFollow(Follow._propertyname_in_atom301);
				propertyname44=propertyname();
				PopFollow();

				adaptor.AddChild(root_0, propertyname44.Tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:51:4: '(' filterexpression ')'
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(51, 4);
				char_literal45=(IToken)Match(input,32,Follow._32_in_atom307); 
				char_literal45_tree = (object)adaptor.Create(char_literal45);
				adaptor.AddChild(root_0, char_literal45_tree);
				DebugLocation(51, 8);
				PushFollow(Follow._filterexpression_in_atom309);
				filterexpression46=filterexpression();
				PopFollow();

				adaptor.AddChild(root_0, filterexpression46.Tree);
				DebugLocation(51, 25);
				char_literal47=(IToken)Match(input,33,Follow._33_in_atom311); 
				char_literal47_tree = (object)adaptor.Create(char_literal47);
				adaptor.AddChild(root_0, char_literal47_tree);

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:52:4: ( ( INT )+ | BOOL | STRING | DATETIME )
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(52, 4);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:52:4: ( ( INT )+ | BOOL | STRING | DATETIME )
				int alt13=4;
				try { DebugEnterSubRule(13);
				try { DebugEnterDecision(13, false);
				switch (input.LA(1))
				{
				case INT:
					{
					alt13 = 1;
					}
					break;
				case BOOL:
					{
					alt13 = 2;
					}
					break;
				case STRING:
					{
					alt13 = 3;
					}
					break;
				case DATETIME:
					{
					alt13 = 4;
					}
					break;
				default:
					{
						NoViableAltException nvae = new NoViableAltException("", 13, 0, input, 1);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}

				} finally { DebugExitDecision(13); }
				switch (alt13)
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:52:5: ( INT )+
					{
					DebugLocation(52, 5);
					// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:52:5: ( INT )+
					int cnt12=0;
					try { DebugEnterSubRule(12);
					while (true)
					{
						int alt12=2;
						try { DebugEnterDecision(12, false);
						int LA12_1 = input.LA(1);

						if ((LA12_1==INT))
						{
							alt12 = 1;
						}


						} finally { DebugExitDecision(12); }
						switch (alt12)
						{
						case 1:
							DebugEnterAlt(1);
							// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:52:5: INT
							{
							DebugLocation(52, 5);
							INT48=(IToken)Match(input,INT,Follow._INT_in_atom317); 
							INT48_tree = (object)adaptor.Create(INT48);
							adaptor.AddChild(root_0, INT48_tree);

							}
							break;

						default:
							if (cnt12 >= 1)
								goto loop12;

							EarlyExitException eee12 = new EarlyExitException( 12, input );
							DebugRecognitionException(eee12);
							throw eee12;
						}
						cnt12++;
					}
					loop12:
						;

					} finally { DebugExitSubRule(12); }


					}
					break;
				case 2:
					DebugEnterAlt(2);
					// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:52:12: BOOL
					{
					DebugLocation(52, 12);
					BOOL49=(IToken)Match(input,BOOL,Follow._BOOL_in_atom322); 
					BOOL49_tree = (object)adaptor.Create(BOOL49);
					adaptor.AddChild(root_0, BOOL49_tree);

					}
					break;
				case 3:
					DebugEnterAlt(3);
					// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:52:19: STRING
					{
					DebugLocation(52, 19);
					STRING50=(IToken)Match(input,STRING,Follow._STRING_in_atom326); 
					STRING50_tree = (object)adaptor.Create(STRING50);
					adaptor.AddChild(root_0, STRING50_tree);

					}
					break;
				case 4:
					DebugEnterAlt(4);
					// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:52:28: DATETIME
					{
					DebugLocation(52, 28);
					DATETIME51=(IToken)Match(input,DATETIME,Follow._DATETIME_in_atom330); 
					DATETIME51_tree = (object)adaptor.Create(DATETIME51);
					adaptor.AddChild(root_0, DATETIME51_tree);

					}
					break;

				}
				} finally { DebugExitSubRule(13); }


				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("atom", 13);
			LeaveRule("atom", 13);
			LeaveRule_atom();
		}
		DebugLocation(52, 36);
		} finally { DebugExitRule(GrammarFileName, "atom"); }
		return retval;

	}
	// $ANTLR end "atom"

	partial void EnterRule_orderby();
	partial void LeaveRule_orderby();
	// $ANTLR start "orderby"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:54:1: orderby : ORDERBY ^ orderbylist ;
	[GrammarRule("orderby")]
	private AstParserRuleReturnScope<object, IToken> orderby()
	{
		EnterRule_orderby();
		EnterRule("orderby", 14);
		TraceIn("orderby", 14);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken ORDERBY52 = default(IToken);
		AstParserRuleReturnScope<object, IToken> orderbylist53 = default(AstParserRuleReturnScope<object, IToken>);

		object ORDERBY52_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "orderby");
		DebugLocation(54, 23);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:55:2: ( ORDERBY ^ orderbylist )
			DebugEnterAlt(1);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:55:4: ORDERBY ^ orderbylist
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(55, 11);
			ORDERBY52=(IToken)Match(input,ORDERBY,Follow._ORDERBY_in_orderby340); 
			ORDERBY52_tree = (object)adaptor.Create(ORDERBY52);
			root_0 = (object)adaptor.BecomeRoot(ORDERBY52_tree, root_0);
			DebugLocation(55, 13);
			PushFollow(Follow._orderbylist_in_orderby343);
			orderbylist53=orderbylist();
			PopFollow();

			adaptor.AddChild(root_0, orderbylist53.Tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("orderby", 14);
			LeaveRule("orderby", 14);
			LeaveRule_orderby();
		}
		DebugLocation(55, 23);
		} finally { DebugExitRule(GrammarFileName, "orderby"); }
		return retval;

	}
	// $ANTLR end "orderby"

	partial void EnterRule_orderbylist();
	partial void LeaveRule_orderbylist();
	// $ANTLR start "orderbylist"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:57:1: orderbylist : orderpropertyname ( ',' ! orderpropertyname )* ;
	[GrammarRule("orderbylist")]
	private AstParserRuleReturnScope<object, IToken> orderbylist()
	{
		EnterRule_orderbylist();
		EnterRule("orderbylist", 15);
		TraceIn("orderbylist", 15);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken char_literal55 = default(IToken);
		AstParserRuleReturnScope<object, IToken> orderpropertyname54 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> orderpropertyname56 = default(AstParserRuleReturnScope<object, IToken>);

		object char_literal55_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "orderbylist");
		DebugLocation(57, 46);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:58:2: ( orderpropertyname ( ',' ! orderpropertyname )* )
			DebugEnterAlt(1);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:58:4: orderpropertyname ( ',' ! orderpropertyname )*
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(58, 4);
			PushFollow(Follow._orderpropertyname_in_orderbylist353);
			orderpropertyname54=orderpropertyname();
			PopFollow();

			adaptor.AddChild(root_0, orderpropertyname54.Tree);
			DebugLocation(58, 22);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:58:22: ( ',' ! orderpropertyname )*
			try { DebugEnterSubRule(15);
			while (true)
			{
				int alt15=2;
				try { DebugEnterDecision(15, false);
				int LA15_1 = input.LA(1);

				if ((LA15_1==34))
				{
					alt15 = 1;
				}


				} finally { DebugExitDecision(15); }
				switch ( alt15 )
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:58:23: ',' ! orderpropertyname
					{
					DebugLocation(58, 26);
					char_literal55=(IToken)Match(input,34,Follow._34_in_orderbylist356); 
					DebugLocation(58, 28);
					PushFollow(Follow._orderpropertyname_in_orderbylist359);
					orderpropertyname56=orderpropertyname();
					PopFollow();

					adaptor.AddChild(root_0, orderpropertyname56.Tree);

					}
					break;

				default:
					goto loop15;
				}
			}

			loop15:
				;

			} finally { DebugExitSubRule(15); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("orderbylist", 15);
			LeaveRule("orderbylist", 15);
			LeaveRule_orderbylist();
		}
		DebugLocation(58, 46);
		} finally { DebugExitRule(GrammarFileName, "orderbylist"); }
		return retval;

	}
	// $ANTLR end "orderbylist"

	partial void EnterRule_orderpropertyname();
	partial void LeaveRule_orderpropertyname();
	// $ANTLR start "orderpropertyname"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:60:1: orderpropertyname : ( propertyname -> ^( ASC propertyname ) | propertyname ( SPACE ! ( ASC | DESC ) ^) );
	[GrammarRule("orderpropertyname")]
	private AstParserRuleReturnScope<object, IToken> orderpropertyname()
	{
		EnterRule_orderpropertyname();
		EnterRule("orderpropertyname", 16);
		TraceIn("orderpropertyname", 16);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken SPACE59 = default(IToken);
		IToken set60 = default(IToken);
		AstParserRuleReturnScope<object, IToken> propertyname57 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> propertyname58 = default(AstParserRuleReturnScope<object, IToken>);

		object SPACE59_tree = default(object);
		object set60_tree = default(object);
		RewriteRuleSubtreeStream stream_propertyname=new RewriteRuleSubtreeStream(adaptor,"rule propertyname");
		try { DebugEnterRule(GrammarFileName, "orderpropertyname");
		DebugLocation(60, 39);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:61:2: ( propertyname -> ^( ASC propertyname ) | propertyname ( SPACE ! ( ASC | DESC ) ^) )
			int alt16=2;
			try { DebugEnterDecision(16, false);
			try
			{
				alt16 = dfa16.Predict(input);
			}
			catch (NoViableAltException nvae)
			{
				DebugRecognitionException(nvae);
				throw;
			}
			} finally { DebugExitDecision(16); }
			switch (alt16)
			{
			case 1:
				DebugEnterAlt(1);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:61:4: propertyname
				{
				DebugLocation(61, 4);
				PushFollow(Follow._propertyname_in_orderpropertyname370);
				propertyname57=propertyname();
				PopFollow();

				stream_propertyname.Add(propertyname57.Tree);


				{
				// AST REWRITE
				// elements: propertyname
				// token labels: 
				// rule labels: retval
				// token list labels: 
				// rule list labels: 
				// wildcard labels: 
				retval.Tree = root_0;
				RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

				root_0 = (object)adaptor.Nil();
				// 61:17: -> ^( ASC propertyname )
				{
					DebugLocation(61, 20);
					// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:61:20: ^( ASC propertyname )
					{
					object root_1 = (object)adaptor.Nil();
					DebugLocation(61, 22);
					root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(ASC, "ASC"), root_1);

					DebugLocation(61, 26);
					adaptor.AddChild(root_1, stream_propertyname.NextTree());

					adaptor.AddChild(root_0, root_1);
					}

				}

				retval.Tree = root_0;
				}

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:62:5: propertyname ( SPACE ! ( ASC | DESC ) ^)
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(62, 5);
				PushFollow(Follow._propertyname_in_orderpropertyname384);
				propertyname58=propertyname();
				PopFollow();

				adaptor.AddChild(root_0, propertyname58.Tree);
				DebugLocation(62, 18);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:62:18: ( SPACE ! ( ASC | DESC ) ^)
				DebugEnterAlt(1);
				// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:62:19: SPACE ! ( ASC | DESC ) ^
				{
				DebugLocation(62, 24);
				SPACE59=(IToken)Match(input,SPACE,Follow._SPACE_in_orderpropertyname387); 
				DebugLocation(62, 38);

				set60=(IToken)input.LT(1);
				set60=(IToken)input.LT(1);
				if (input.LA(1)==ASC||input.LA(1)==DESC)
				{
					input.Consume();
					root_0 = (object)adaptor.BecomeRoot((object)adaptor.Create(set60), root_0);
					state.errorRecovery=false;
				}
				else
				{
					MismatchedSetException mse = new MismatchedSetException(null,input);
					DebugRecognitionException(mse);
					throw mse;
				}


				}


				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("orderpropertyname", 16);
			LeaveRule("orderpropertyname", 16);
			LeaveRule_orderpropertyname();
		}
		DebugLocation(62, 39);
		} finally { DebugExitRule(GrammarFileName, "orderpropertyname"); }
		return retval;

	}
	// $ANTLR end "orderpropertyname"

	partial void EnterRule_propertyname();
	partial void LeaveRule_propertyname();
	// $ANTLR start "propertyname"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:64:1: propertyname : IDENTIFIER ( '/' IDENTIFIER )* ;
	[GrammarRule("propertyname")]
	private AstParserRuleReturnScope<object, IToken> propertyname()
	{
		EnterRule_propertyname();
		EnterRule("propertyname", 17);
		TraceIn("propertyname", 17);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken IDENTIFIER61 = default(IToken);
		IToken char_literal62 = default(IToken);
		IToken IDENTIFIER63 = default(IToken);

		object IDENTIFIER61_tree = default(object);
		object char_literal62_tree = default(object);
		object IDENTIFIER63_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "propertyname");
		DebugLocation(64, 32);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:65:2: ( IDENTIFIER ( '/' IDENTIFIER )* )
			DebugEnterAlt(1);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:65:4: IDENTIFIER ( '/' IDENTIFIER )*
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(65, 4);
			IDENTIFIER61=(IToken)Match(input,IDENTIFIER,Follow._IDENTIFIER_in_propertyname407); 
			IDENTIFIER61_tree = (object)adaptor.Create(IDENTIFIER61);
			adaptor.AddChild(root_0, IDENTIFIER61_tree);
			DebugLocation(65, 16);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:65:16: ( '/' IDENTIFIER )*
			try { DebugEnterSubRule(17);
			while (true)
			{
				int alt17=2;
				try { DebugEnterDecision(17, false);
				int LA17_1 = input.LA(1);

				if ((LA17_1==35))
				{
					alt17 = 1;
				}


				} finally { DebugExitDecision(17); }
				switch ( alt17 )
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:65:17: '/' IDENTIFIER
					{
					DebugLocation(65, 17);
					char_literal62=(IToken)Match(input,35,Follow._35_in_propertyname411); 
					char_literal62_tree = (object)adaptor.Create(char_literal62);
					adaptor.AddChild(root_0, char_literal62_tree);
					DebugLocation(65, 21);
					IDENTIFIER63=(IToken)Match(input,IDENTIFIER,Follow._IDENTIFIER_in_propertyname413); 
					IDENTIFIER63_tree = (object)adaptor.Create(IDENTIFIER63);
					adaptor.AddChild(root_0, IDENTIFIER63_tree);

					}
					break;

				default:
					goto loop17;
				}
			}

			loop17:
				;

			} finally { DebugExitSubRule(17); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("propertyname", 17);
			LeaveRule("propertyname", 17);
			LeaveRule_propertyname();
		}
		DebugLocation(65, 32);
		} finally { DebugExitRule(GrammarFileName, "propertyname"); }
		return retval;

	}
	// $ANTLR end "propertyname"

	partial void EnterRule_filteroperator();
	partial void LeaveRule_filteroperator();
	// $ANTLR start "filteroperator"
	// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:67:1: filteroperator : ( EQUALS | NOTEQUALS | GREATERTHAN | GREATERTHANOREQUAL | LESSTHAN | LESSTHANOREQUAL );
	[GrammarRule("filteroperator")]
	private AstParserRuleReturnScope<object, IToken> filteroperator()
	{
		EnterRule_filteroperator();
		EnterRule("filteroperator", 18);
		TraceIn("filteroperator", 18);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken set64 = default(IToken);

		object set64_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "filteroperator");
		DebugLocation(67, 85);
		try
		{
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:68:2: ( EQUALS | NOTEQUALS | GREATERTHAN | GREATERTHANOREQUAL | LESSTHAN | LESSTHANOREQUAL )
			DebugEnterAlt(1);
			// D:\\Code\\LinqToQuerystring\\LinqToQuerystring\\LinqToQuerystring.g:
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(68, 2);

			set64=(IToken)input.LT(1);
			if (input.LA(1)==EQUALS||(input.LA(1)>=GREATERTHAN && input.LA(1)<=GREATERTHANOREQUAL)||(input.LA(1)>=LESSTHAN && input.LA(1)<=LESSTHANOREQUAL)||input.LA(1)==NOTEQUALS)
			{
				input.Consume();
				adaptor.AddChild(root_0, (object)adaptor.Create(set64));
				state.errorRecovery=false;
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				throw mse;
			}


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("filteroperator", 18);
			LeaveRule("filteroperator", 18);
			LeaveRule_filteroperator();
		}
		DebugLocation(68, 85);
		} finally { DebugExitRule(GrammarFileName, "filteroperator"); }
		return retval;

	}
	// $ANTLR end "filteroperator"
	#endregion Rules


	#region DFA
	private DFA16 dfa16;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa16 = new DFA16( this );
	}

	private class DFA16 : DFA
	{
		private const string DFA16_eotS =
			"\x6\xFFFF";
		private const string DFA16_eofS =
			"\x1\xFFFF\x1\x3\x3\xFFFF\x1\x3";
		private const string DFA16_minS =
			"\x1\xF\x1\xC\x1\xF\x2\xFFFF\x1\xC";
		private const string DFA16_maxS =
			"\x1\xF\x1\x23\x1\xF\x2\xFFFF\x1\x23";
		private const string DFA16_acceptS =
			"\x3\xFFFF\x1\x1\x1\x2\x1\xFFFF";
		private const string DFA16_specialS =
			"\x6\xFFFF}>";
		private static readonly string[] DFA16_transitionS =
			{
				"\x1\x1",
				"\x1\x3\x3\xFFFF\x1\x3\x8\xFFFF\x3\x3\x1\x4\x1\xFFFF\x2\x3\x2\xFFFF\x1"+
				"\x3\x1\x2",
				"\x1\x5",
				"",
				"",
				"\x1\x3\x3\xFFFF\x1\x3\x8\xFFFF\x3\x3\x1\x4\x1\xFFFF\x2\x3\x2\xFFFF\x1"+
				"\x3\x1\x2"
			};

		private static readonly short[] DFA16_eot = DFA.UnpackEncodedString(DFA16_eotS);
		private static readonly short[] DFA16_eof = DFA.UnpackEncodedString(DFA16_eofS);
		private static readonly char[] DFA16_min = DFA.UnpackEncodedStringToUnsignedChars(DFA16_minS);
		private static readonly char[] DFA16_max = DFA.UnpackEncodedStringToUnsignedChars(DFA16_maxS);
		private static readonly short[] DFA16_accept = DFA.UnpackEncodedString(DFA16_acceptS);
		private static readonly short[] DFA16_special = DFA.UnpackEncodedString(DFA16_specialS);
		private static readonly short[][] DFA16_transition;

		static DFA16()
		{
			int numStates = DFA16_transitionS.Length;
			DFA16_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA16_transition[i] = DFA.UnpackEncodedString(DFA16_transitionS[i]);
			}
		}

		public DFA16( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 16;
			this.eot = DFA16_eot;
			this.eof = DFA16_eof;
			this.min = DFA16_min;
			this.max = DFA16_max;
			this.accept = DFA16_accept;
			this.special = DFA16_special;
			this.transition = DFA16_transition;
		}

		public override string Description { get { return "60:1: orderpropertyname : ( propertyname -> ^( ASC propertyname ) | propertyname ( SPACE ! ( ASC | DESC ) ^) );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}


	#endregion DFA

	#region Follow sets
	private static class Follow
	{
		public static readonly BitSet _param_in_prog55 = new BitSet(new ulong[]{0xCE011002UL});
		public static readonly BitSet _31_in_prog58 = new BitSet(new ulong[]{0x4E011000UL});
		public static readonly BitSet _param_in_prog61 = new BitSet(new ulong[]{0xCE011002UL});
		public static readonly BitSet _orderby_in_param74 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _top_in_param78 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _skip_in_param82 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _filter_in_param86 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _select_in_param90 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _inlinecount_in_param94 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _SKIP_in_skip105 = new BitSet(new ulong[]{0x20000UL});
		public static readonly BitSet _INT_in_skip108 = new BitSet(new ulong[]{0x20002UL});
		public static readonly BitSet _TOP_in_top119 = new BitSet(new ulong[]{0x20000UL});
		public static readonly BitSet _INT_in_top122 = new BitSet(new ulong[]{0x20002UL});
		public static readonly BitSet _FILTER_in_filter133 = new BitSet(new ulong[]{0x120428300UL});
		public static readonly BitSet _filterexpression_in_filter136 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _SELECT_in_select146 = new BitSet(new ulong[]{0x8000UL});
		public static readonly BitSet _propertyname_in_select149 = new BitSet(new ulong[]{0x400000002UL});
		public static readonly BitSet _34_in_select152 = new BitSet(new ulong[]{0x8000UL});
		public static readonly BitSet _propertyname_in_select155 = new BitSet(new ulong[]{0x400000002UL});
		public static readonly BitSet _INLINECOUNT_in_inlinecount167 = new BitSet(new ulong[]{0x10UL});
		public static readonly BitSet _ALLPAGES_in_inlinecount170 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _INLINECOUNT_in_inlinecount175 = new BitSet(new ulong[]{0x200000UL});
		public static readonly BitSet _NONE_in_inlinecount177 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _orexpression_in_filterexpression189 = new BitSet(new ulong[]{0x10000002UL});
		public static readonly BitSet _SPACE_in_filterexpression192 = new BitSet(new ulong[]{0x1000000UL});
		public static readonly BitSet _OR_in_filterexpression195 = new BitSet(new ulong[]{0x10000000UL});
		public static readonly BitSet _SPACE_in_filterexpression198 = new BitSet(new ulong[]{0x120428300UL});
		public static readonly BitSet _orexpression_in_filterexpression201 = new BitSet(new ulong[]{0x10000002UL});
		public static readonly BitSet _andexpression_in_orexpression213 = new BitSet(new ulong[]{0x10000002UL});
		public static readonly BitSet _SPACE_in_orexpression216 = new BitSet(new ulong[]{0x20UL});
		public static readonly BitSet _AND_in_orexpression219 = new BitSet(new ulong[]{0x10000000UL});
		public static readonly BitSet _SPACE_in_orexpression222 = new BitSet(new ulong[]{0x120428300UL});
		public static readonly BitSet _andexpression_in_orexpression225 = new BitSet(new ulong[]{0x10000002UL});
		public static readonly BitSet _NOT_in_andexpression237 = new BitSet(new ulong[]{0x10000000UL});
		public static readonly BitSet _SPACE_in_andexpression240 = new BitSet(new ulong[]{0x120028300UL});
		public static readonly BitSet _booleanexpression_in_andexpression242 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _booleanexpression_in_andexpression247 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _atom_in_booleanexpression258 = new BitSet(new ulong[]{0x10000000UL});
		public static readonly BitSet _SPACE_in_booleanexpression261 = new BitSet(new ulong[]{0x8C6800UL});
		public static readonly BitSet _filteroperator_in_booleanexpression264 = new BitSet(new ulong[]{0x10000000UL});
		public static readonly BitSet _SPACE_in_booleanexpression267 = new BitSet(new ulong[]{0x120028300UL});
		public static readonly BitSet _atom_in_booleanexpression270 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _implicit_in_booleanexpression274 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _propertyname_in_atom301 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _32_in_atom307 = new BitSet(new ulong[]{0x120428300UL});
		public static readonly BitSet _filterexpression_in_atom309 = new BitSet(new ulong[]{0x200000000UL});
		public static readonly BitSet _33_in_atom311 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _INT_in_atom317 = new BitSet(new ulong[]{0x20002UL});
		public static readonly BitSet _BOOL_in_atom322 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _STRING_in_atom326 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _DATETIME_in_atom330 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ORDERBY_in_orderby340 = new BitSet(new ulong[]{0x8000UL});
		public static readonly BitSet _orderbylist_in_orderby343 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _orderpropertyname_in_orderbylist353 = new BitSet(new ulong[]{0x400000002UL});
		public static readonly BitSet _34_in_orderbylist356 = new BitSet(new ulong[]{0x8000UL});
		public static readonly BitSet _orderpropertyname_in_orderbylist359 = new BitSet(new ulong[]{0x400000002UL});
		public static readonly BitSet _propertyname_in_orderpropertyname370 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _propertyname_in_orderpropertyname384 = new BitSet(new ulong[]{0x10000000UL});
		public static readonly BitSet _SPACE_in_orderpropertyname387 = new BitSet(new ulong[]{0x440UL});
		public static readonly BitSet _set_in_orderpropertyname390 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _IDENTIFIER_in_propertyname407 = new BitSet(new ulong[]{0x800000002UL});
		public static readonly BitSet _35_in_propertyname411 = new BitSet(new ulong[]{0x8000UL});
		public static readonly BitSet _IDENTIFIER_in_propertyname413 = new BitSet(new ulong[]{0x800000002UL});
	}
	#endregion Follow sets
}

} // namespace  LinqToQuerystring 
